export default [
    'Cement',
    'Cemat',
    'Cemote',
    'Steel',
    'Bricks',
    'Paint',
    'Tiles',
    'Sanitary Ware',
    'Electrical',
    'Plumbing',
    'Hardware',
    'Plywood',
    'Laminates',
    'Kitchen',
    'Home Decor',
    'Lighting',
    'Furniture',
    'Appliances',
    'Safety',
    'Tools',
    'Building Materials',
    'Construction',
    'Wall Finishing',
    'Flooring',
    'Roofing',
    'Ceiling',
    'Doors',
    'Windows',
    'Glass',
    'Water Proofing',
    'Insulation',
    'Landscaping',
    'Gardening',
]