apiVersion: apps/v1
kind: Deployment
metadata:
  name: oms-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oms-backend
  template:
    metadata:
      labels:
        app: oms-backend
    spec:
      containers:
      - name: oms-backend
        image: tashvik/oms-backend:latest
        ports:
        - containerPort: 8080
