apiVersion: v1
kind: Service
metadata:
  name: oms-backend
spec:
  selector:
    app: oms-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30002
  type: NodePort
