export default [
    'Cement',
    'Steel',
    'Bricks',
    'Paint',
    'Tiles',
    'Sanitary Ware',
    'Electrical',
    'Plumbing',
    'Hardware',
    'Plywood',
    'Laminates',
    'Kitchen',
    'Home Decor',
    'Lighting',
    'Furniture',
    'Appliances',
    'Safety',
    'Tools',
    'Building Materials',
    'Construction',
    'Wall Finishing',
    'Flooring',
    'Roofing',
    'Ceiling',
    'Doors',
    'Windows',
    'Glass',
    'Water Proofing',
    'Insulation',
    'Landscaping',
    'Gardening',
    'Ultratech',
     'ACC',
     'Ambuja',
     'Birla Gold',
     'Shree Cement',
     'JSW Cement',
     'Dalmia',
     'JK Lakshmi',
     'Wonder Cement',
     'Bangur Cement',
     'Bangur',   
     'Shalimar',
]